version: "2"
services:

  bitcored:
    image: dalijolijo/bitcored
    expose:
      - "5888"
    ports:
      - "5889:5889"
    volumes:
      - ./data/bitcored:/data
    command: -rpcuser=electrum -rpcpassword=electrum

  electrumx:
    image: lukechilds/electrumx
    ports:
      - "50002:50002"
    volumes:
      - ./data/electrumx:/data
    environment:
      - DAEMON_URL=http://electrum:electrum@bitcored:5888
      - COIN=Bitcore
      - RPC_HOST=127.0.0.1
      - MAX_SESSIONS=100000 
